repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: check-ast
    -   id: check-docstring-first
    -   id: end-of-file-fixer
    -   id: check-builtin-literals
    -   id: debug-statements
    -   id: forbid-new-submodules
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/zricethezav/gitleaks
    rev: v7.6.1
    hooks:
    -   id: gitleaks
        name: Detect hardcoded secrets
        description: Detect hardcoded secrets using Gitleaks
        args: [--debug, --verbose, --repo-url, .]
